### ISSUE TITLE
Dalli triggering I18n::InvalidLocale error if I don't have :en in config.i18n.available_locales?

### ISSUE THREAD

**Issue by x-ji** [mperham/dalli#516]
Somehow I get the following error when I was trying to invoke `Rails.cache.fetch`:

```
[FATALFATALFATAL]
I18n::InvalidLocale - :en is not a valid locale:
  i18n (0.7.0) lib/i18n.rb:284:in `enforce_available_locales!'
  i18n (0.7.0) lib/i18n.rb:151:in `translate'
  activesupport (4.2.0) lib/active_support/core_ext/array/conversions.rb:68:in `to_sentence'
  activesupport (4.2.0) lib/active_support/duration.rb:94:in `inspect'
  dalli (2.7.2) lib/active_support/cache/dalli_store.rb:355:in `log'
  dalli (2.7.2) lib/active_support/cache/dalli_store.rb:346:in `instrument'
  dalli (2.7.2) lib/active_support/cache/dalli_store.rb:90:in `fetch'
  app/controllers/users_controller.rb:16:in `create'
```

After I added `:en` to `config.i18n.available_locales`, the issue disappeared.

However, the problem is that our app is not targeted to an English-speaking audience and therefore is not supposed to have `:en` as an available locale.

Is there any way around it?

Thanks!

**Comment by petergoldstein** [comment]
Have you set I18n.default_locale anywhere?  If you check I18n.default_locale on the Rails console, what is it?

**Comment by x-ji** [comment]
Yeah I set it at the same place as I set available_locales. I checked it and it's `:zh-CN`

**Comment by petergoldstein** [comment]
Interesting.  This is an ActiveSupport bug in Duration. -- http://apidock.com/rails/v4.1.8/ActiveSupport/Duration/inspect

It was just fixed on Rails master - https://github.com/rails/rails/commit/f76d1aa54d25670f6b6d635ad0350cea8b88c706 and was backported to the Rails 4.1 and 4.2 branches.  

My only suggestion is to update to Rails 4.2.1 when it is released (or use an RC release in the interim)

Closing, as this isn't a Dalli issue.
