### ISSUE TITLE
crash due to reading cached value that is an unknown class

### ISSUE THREAD

**Issue by dspeterson** [mperham/dalli#517]
I'm not sure if this is really a legitimate bug, but it's probably worth thinking about whether there is a more graceful way to handle the following unusual case:

I have two hosts running Rails and using the same memcache cluster.  First I do the following in a Rails console on host one:

[prod] 48:(main)> class MyTestClass
               >> end  
=> nil
[prod] 49:(main)> Rails.cache.write('test_cache_key', MyTestClass)
=> true
[prod] 50:(main)> 

Then I do the following in a Rails console on host two (note: MyTestClass is not defined in the Rails console on host two):

[prod] 52:(main)> Rails.cache.read('test_cache_key')
Unexpected exception in Dalli: NameError: uninitialized constant MyTestClass
This is a bug in Dalli, please enter an issue in Github if it does not already exist.
/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:226:in `const_get'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:226:in `block in constantize'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `each'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `inject'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:224:in `constantize'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/core_ext/marshal.rb:10:in `rescue in load_with_autoloading'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/core_ext/marshal.rb:6:in `load_with_autoloading'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:423:in `deserialize'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:479:in `generic_response'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:256:in `get'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/server.rb:60:in `request'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/options.rb:18:in `block in request'
	/usr/local/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/options.rb:17:in `request'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/client.rb:348:in `perform'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/dalli/client.rb:62:in `get'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:229:in `read_entry'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/cache/strategy/local_cache.rb:129:in `read_entry'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:95:in `block in read'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:291:in `block in instrument'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:291:in `instrument'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/dalli-2.6.4/lib/active_support/cache/dalli_store.rb:94:in `read'
	(pry):7:in `<main>'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:328:in `eval'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:328:in `evaluate_ruby'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:278:in `re'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:254:in `rep'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:234:in `block (3 levels) in repl'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:232:in `loop'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:232:in `block (2 levels) in repl'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:231:in `catch'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:231:in `block in repl'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:230:in `catch'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_instance.rb:230:in `repl'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-0.9.12.6/lib/pry/pry_class.rb:169:in `start'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/pry-byebug-1.3.2/lib/pry-byebug/pry_ext.rb:19:in `start_with_pry_byebug'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/commands/console.rb:90:in `start'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/commands/console.rb:9:in `start'
	/var/www/apps/academia.edu/shared/bundle/ruby/2.0.0/gems/railties-4.0.13/lib/rails/commands.rb:62:in `<top (required)>'
	script/rails:6:in `require'
	script/rails:6:in `<main>'
=> nil
[prod] 53:(main)>

**Comment by petergoldstein** [comment]
That's not a bug in Dalli.  And it basically tells you the problem at the top of the stack trace:

    Unexpected exception in Dalli: NameError: uninitialized constant MyTestClass

Not sure how it would handle it more gracefully, other than by removing the "This is a bug in Dalli" message, which has been discussed elsewhere.  It should throw an exception, and that exception should tell you the problem.  It does both those things.

**Comment by dspeterson** [comment]
Ok, sounds good.  I'm not too familiar with Dalli, so I wasn't sure if it was worth reporting.
