### ISSUE TITLE
Release since 2.7.2?

### ISSUE THREAD

**Issue by tpitale** [mperham/dalli#518]
/cc @petergoldstein @mperham 

There appears to be a large number of commits since the last official/gem release of Dalli. Can we push a new gem sometime soon?

We're specifically looking for https://github.com/mperham/dalli/pull/492 which was merged ~6 months ago.

Thank you!

**Comment by petergoldstein** [comment]
@tpitale I don't currently have the ability to publish new Dalli gems, but if @mperham wants to approve me I'm happy to publish an updated version this weekend.

**Comment by mperham** [comment]
Ack, I never gave @petergoldstein push rights.  What's your Rubygems email?

**Comment by petergoldstein** [comment]
@mperham peter.m.goldstein@gmail.com

**Comment by mperham** [comment]
Done!

**Comment by petergoldstein** [comment]
@mperham Thanks.  I'll publish a version this weekend.

**Comment by tpitale** [comment]
Thank you so much!

**Comment by petergoldstein** [comment]
I just pushed 2.7.3.

**Comment by tpitale** [comment]
Thanks @petergoldstein!
