### ISSUE TITLE
Uninitialized constant UNIXSocket under windows (torquebox/jruby)

### ISSUE THREAD

**Issue by fpauser** [mperham/dalli#523]
Seems to be a problem with https://github.com/mperham/dalli/blob/354e24e2c2be3cc6ee9003fe88df3a6b95b17e83/lib/dalli/socket.rb#L129

**Comment by dfens** [comment]
Did you update gem lately? Also unix sockets are not existing on windows that should be taken care of

**Comment by fpauser** [comment]
We updated our rails-app to use dalli-2.7.3 instead of dalli-2.7.2 - which gave us the mentioned error. Going back to 2.7.2 fixes the problem for us, so this seems to be a problem in 2.7.3.

**Comment by dfens** [comment]
Referenced commit should fix the issue. Probably would be fixed in 2.7.4

**Comment by fpauser** [comment]
Nice, this should fix it! ;)

**Comment by dfens** [comment]
@fpauser are you able to test with this fork?

**Comment by fpauser** [comment]
I'll test it and report it here.

**Comment by fpauser** [comment]
Tested it and created a fix for the fix ;) - see dfens/dalli#1

**Comment by dfens** [comment]
Thanks, I will merge this if https://github.com/mperham/dalli/pull/524 test passes

**Comment by petergoldstein** [comment]
Argh.  This should have occurred to me when reviewing the patch.  My apologies.

**Comment by dfens** [comment]
@petergoldstein no worries - this fix seems ok however tests are not passing on unknown reason to me - can you please trigger travis build?

**Comment by petergoldstein** [comment]
@dfens I already have.

On a related note, any chance you could squash the commits before I merge the PR?  And do the specs run clean on Windows, or do we need to add an RbConfig block to some of the specs?

**Comment by dfens** [comment]
Squashed to 2 commits

**Comment by dfens** [comment]
@petergoldstein I am not able to tell if works clean on windows - @fpauser should be able to tell for sure

**Comment by petergoldstein** [comment]
@fpauser Should be fixed with 2.7.4.  Please let me know if you run into any additional problems.  Thanks.
