### ISSUE TITLE
Reading and Writing to different servers?

### ISSUE THREAD

**Issue by brandonsturgeon** [mperham/dalli#527]
On our production server we have a large set of cached data. It would be very helpful to be able to access this data from our development environment, because otherwise we have to generate it ourselves which ends up taking awhile. We do NOT want to write any data to our production's cache from our development environment, we need to make sure this is impossible to do.

It would be very handy to set a read_server separate from a write_server. That way we can read the data from Production, but any data that needs to be written will be written to a local cache.

Is this do-able? If so, how easy would this be?

**Comment by petergoldstein** [comment]
Implementing a feature like this would require a lot of network access level modifications to Dalli.  It would also require us to explicitly forbid CAS behavior when the read_server and write_server are different.  Thus, a lot of work, and a lot of code that is likely to be extremely fragile going forward.

As this is a feature that addresses a very specific and unusual use case, for which there is already a functional solution (generating the data for the development server), I don't feel this feature would be a good addition to Dalli.

**Comment by mperham** [comment]
Assuming you are using Rails.cache only, you could build a Rails cache adapter which stubbed out write operations and use that instead of :dalli_store in development.
