### ISSUE TITLE
Rails.cache.write(key, value, { compress: true }) doesn't work

### ISSUE THREAD

**Issue by aMasashiOgawa** [mperham/dalli#530]
I have a question.

```
config.cache_store = :dalli_store, { compress: true }
```
This works well, but the following doesn't work. The `value` is not compressed.
```
Rails.cache.write(key, value, { compress: true })
```
Is this expected behavior?

I would like you to make the `compress` option enabled when calling `Rails.cache.write`.
https://github.com/mperham/dalli/blob/master/lib/dalli/server.rb#L416
```
-       if @options[:compress] && value.bytesize >= @options[:compression_min_size] &&
+       if (@options[:compress] || options[:compress]) && value.bytesize >= @options[:compression_min_size] &&
```

**Comment by petergoldstein** [comment]
Based on the Rails docs here - http://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html - I think this is an appropriate change.  Can you put together a PR?

**Comment by aMasashiOgawa** [comment]
Thank you for your comment. I created PR. Please review following.
https://github.com/mperham/dalli/pull/536

**Comment by petergoldstein** [comment]
PR merged.  Thanks!
