### ISSUE TITLE
Question regarding pool_size with Puma

### ISSUE THREAD

**Issue by mwalsher** [mperham/dalli#541]
This is probably out of the scope of things here, but regarding the pool_size setting, what factors need to be considered in determining what to set it to?

For example, if I have two puma workers, each with a maximum of 74 threads, would it make sense to simply set pool_size to 74?

**Comment by mperham** [comment]
You can do that or you can give the 74 threads a smaller pool of connections to share, say 25.  The more you use Dalli, the more connections you should provide.  Many people use a commercial memcached service where they have a limited number of connections.  Being able to limit the connections per-process is critical to staying within that limit during heavy traffic.

**Comment by mwalsher** [comment]
Good point, thanks!
